name: hsr 
cls: hsr.models.hsr.HSR
max_steps: 150000
val_steps: 1500
is_continue: False
learning_rate: 5.0e-4
decay_rate: 0.1
decay_steps: ${model.max_steps}
smpl_init: True
opt_smpl: True
opt_camera_pose: False
val_render_image: True
test_render_image: True
test_save_numerical_results: False
update_canonical_mesh: True
fg_implicit_network:
  feature_vector_size: 256
  dim_pose_embed: 0
  d_in: 3
  d_out: 1
  dims: [256, 256, 256, 256, 256, 256, 256, 256]
  init: null 
  bias: 0.6
  skip_in: [4]
  weight_norm: True
  embedder_mode: fourier
  multires: 6
  cond: smpl
  scene_bounding_sphere: 3.0
  inside_outside: False
fg_rendering_network:
  feature_vector_size: 256
  mode: idr_pose_no_view
  dim_cond_embed: 8
  d_in: 14
  d_out: 3
  dims: [256, 256, 256, 256]
  weight_norm: True
  multires_view: -1
bg_implicit_network:
  feature_vector_size: 256
  dim_pose_embed: 0
  d_in: 3
  d_out: 1
  dims: [256, 256, 256, 256, 256, 256, 256, 256]
  init: geometry
  bias: 2.0
  skip_in: [4]
  weight_norm: True
  embedder_mode: fourier
  multires: 6
  cond: null
  scene_bounding_sphere: ${model.fg_implicit_network.scene_bounding_sphere}
  inside_outside: True
bg_rendering_network:
  feature_vector_size: 256
  mode: idr_frame_encoding
  dim_frame_encoding: 32
  d_in: 9
  d_out: 3
  dims: [256, 256]
  weight_norm: True
  multires_view: 4
fg_density:
  params_init: { beta: 0.1 }
  beta_min: 0.0001
bg_density:
  params_init: { beta: 0.1 }
  beta_min: 0.0001
fg_ray_sampler:
  near: 0.0
  N_samples: 64
  N_samples_eval: 128
  N_samples_extra: 32
  eps: 0.1
  beta_iters: 10
  max_total_iters: 5
  add_tiny: 1.0e-6
bg_ray_sampler:
  near: 0.0
  N_samples: 64
  N_samples_eval: 128
  N_samples_extra: 32
  eps: 0.1
  beta_iters: 10
  max_total_iters: 5
  add_tiny: 1.0e-6
loss:
  eikonal_weight: 0.1
  depth_weight: 0.1
  mask_weight: 0.1
  normal_l1_weight: 0.05
  normal_cos_weight: 0.05
  normal_smooth_weight: 0.005
  density_weight: 0.005
  in_surface_weight: 0.01
  off_surface_weight: 0.003
  penetration_weight: 50
  s3im_weight: 0.1
  max_steps: ${model.max_steps}