gender: male
name: real 
train:
  subject: demo
  data_dir: real/demo/processed
  start_frame: 0
  end_frame: 77
  skip_step: 1
  exclude_frames: null
  img_resize_factor: 1

  num_sample: 1024
  batch_size: 1
  drop_last: False
  shuffle: True
  worker: 8
  sampling_strategy: weighted
  bbox_sampling_ratio: 0.8

val:
  subject: ${dataset.train.subject}
  data_dir: ${dataset.train.data_dir}
  start_frame: ${dataset.train.start_frame}
  end_frame: ${dataset.train.end_frame}
  skip_step: ${dataset.train.skip_step}
  exclude_frames: ${dataset.train.exclude_frames}
  img_resize_factor: 2

  num_sample: -1
  pixel_per_batch: 1024
  batch_size: 1
  drop_last: False
  shuffle: False
  worker: 8

test:
  subject: ${dataset.train.subject}
  data_dir: ${dataset.train.data_dir}
  start_frame: ${dataset.train.start_frame}
  end_frame: ${dataset.train.end_frame}
  skip_step: ${dataset.train.skip_step}
  exclude_frames: ${dataset.train.exclude_frames}
  img_resize_factor: 1

  num_sample: -1
  pixel_per_batch: 1024
  batch_size: 1
  drop_last: False
  shuffle: False
  worker: 8
